[package]
name = "rgba"
version = "0.1.0"
authors = ["Roderick MacCrimmon <r.maccrimm@gmail.com>"]
edition = "2018"

[dependencies]
num-traits = "0.2"
num-derive = "0.3"

[dependencies.gtk]
version = "0.8.1"
features = ["v3_16"]

[dependencies.gio]
version = ""
features = ["v2_44"]